# Generated by Django 4.0 on 2022-01-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_commentmodel_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='post',
        ),
    ]
