# Generated by Django 4.0 on 2022-01-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_commentmodel_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
